name: Publish Package to npmjs
permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Debug npm OIDC
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm config list
      
      - name: Check OIDC identity
        run: |
          echo "JWT: ${ACTIONS_ID_TOKEN_REQUEST_URL}"

      - name: Check OIDC configuration
        run: npm whoami --registry=https://registry.npmjs.org/

      - name: Publish the module
        run: npm publish